// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOQ7ouwFLJYHLcRvDBnkN-0VhJAfATRvM',
    appId: '1:581912961073:web:6706f7cb06a25dbf0fb510',
    messagingSenderId: '581912961073',
    projectId: 'macromaster-6373f',
    authDomain: 'macromaster-6373f.firebaseapp.com',
    storageBucket: 'macromaster-6373f.appspot.com',
    measurementId: 'G-N5Q9WJ7FZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC40J3GwujeWLy6CGND75Ik-qrK6qgUtU',
    appId: '1:581912961073:android:bcb0b71b95dc61930fb510',
    messagingSenderId: '581912961073',
    projectId: 'macromaster-6373f',
    storageBucket: 'macromaster-6373f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVfq77Rqhu-CUUhd4SjMx3uhq41Xt3-x8',
    appId: '1:581912961073:ios:7d721bb33b3131540fb510',
    messagingSenderId: '581912961073',
    projectId: 'macromaster-6373f',
    storageBucket: 'macromaster-6373f.appspot.com',
    iosBundleId: 'com.example.macrotrackr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVfq77Rqhu-CUUhd4SjMx3uhq41Xt3-x8',
    appId: '1:581912961073:ios:28c46348fae151a80fb510',
    messagingSenderId: '581912961073',
    projectId: 'macromaster-6373f',
    storageBucket: 'macromaster-6373f.appspot.com',
    iosBundleId: 'com.example.macrotrackr.RunnerTests',
  );
}
